version: '3.8'

services:
  eureka-server:
    build: ./MicroServicioEureka
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - parcial-network

  microservicio-usuarios:
    build: ./MicroServicioUsuarios
    container_name: microservicio-usuarios
    depends_on:
      - eureka-server
      - postgres
    networks:
      - parcial-network

  microservicio-cursos:
    build: ./MicroServicioCursos
    container_name: microservicio-cursos
    depends_on:
      - eureka-server
      - postgres
    networks:
      - parcial-network

  gateway:
    build: ./MicroServicioSpringGateway
    container_name: gateway
    ports:
      - "8090:8090"
    depends_on:
      - microservicio-usuarios
      - microservicio-cursos
      - eureka-server
    networks:
      - parcial-network

  postgres:
    image: postgres:latest
    container_name: postgresdb
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=db
    ports:
      - "5432:5432"
    networks:
      - parcial-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    networks:
      - parcial-network
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - parcial-network
    depends_on:
      - eureka-server
      - microservicio-usuarios
      - microservicio-cursos
      - gateway

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    networks:
      - parcial-network
    volumes:
      - grafana_data:/var/lib/grafana

networks:
  parcial-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local
  grafana_data:
    driver: local

