global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']


  - job_name: 'eureka-server'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['eureka-server:8761']

  - job_name: 'microservicio-usuarios'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['microservicio-usuarios:8082']

  - job_name: 'microservicio-cursos'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['microservicio-cursos:8081']

  - job_name: 'gateway'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['gateway:8090']
