global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'nginx'
    metrics_path: /stub_status
    static_configs:
      - targets: ['nginx:80']

  - job_name: 'eureka-server'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['eureka-server:8761']

  - job_name: 'microservicio-usuarios'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['microservicio-usuarios:8080']

  - job_name: 'microservicio-cursos'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['microservicio-cursos:8080']

  - job_name: 'gateway'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['gateway:8090']
